-- libinput Lua plugin: drop spurious reverse-direction wheel ticks.
--
-- Worn wheel encoders occasionally emit one or more ticks in the opposite
-- direction in the middle of a scroll. This plugin withholds opposite-direction
-- ticks until it can tell a glitch from a genuine reversal:
--
--   * An opposite tick arriving within CONFIG.window_us of the previous wheel
--     tick is HELD instead of forwarded.
--   * If the next tick continues in the old direction, the held tick(s) were a
--     glitch and are discarded.
--   * Once CONFIG.confirm_ticks consecutive opposite ticks have been held, the
--     reversal is genuine: the older held ticks are re-injected (merged into one
--     frame, via prepend_frame) ahead of the current tick, so no movement is lost.
--   * An opposite tick arriving later than window_us after the previous tick is
--     treated as genuine; any held ticks are released first.
--
-- Known trade-off: a deliberate reversal shorter than confirm_ticks notches,
-- within window_us of the previous notch, is dropped.
--
-- This file expects a `CONFIG` local to be defined ahead of it (generated by
-- the NixOS module):
--   CONFIG.window_us     : integer, microseconds
--   CONFIG.confirm_ticks : integer >= 2
--   CONFIG.debug         : boolean, log drops / confirmations
--   CONFIG.trace         : boolean, log every vertical wheel frame
--   CONFIG.devices       : list of { vid = <int>, pid = <int> }; empty = all mice

libinput:register({1})

local function sign(v)
  if v > 0 then return 1 elseif v < 0 then return -1 else return 0 end
end

local function log(msg)
  if CONFIG.debug then
    libinput:log_info("scroll-reversal-filter: " .. msg)
  end
end

local function trace(msg)
  if CONFIG.trace then
    libinput:log_info("scroll-reversal-filter[trace]: " .. msg)
  end
end

local function wants(device)
  local usages = device:usages()
  if not (usages[evdev.REL_WHEEL] or usages[evdev.REL_WHEEL_HI_RES]) then
    return false
  end

  if #CONFIG.devices == 0 then
    -- Any pointer with a wheel (must also move, to exclude odd non-mice).
    return (usages[evdev.REL_X] and usages[evdev.REL_Y]) and true or false
  end

  local info = device:info()
  for _, m in ipairs(CONFIG.devices) do
    if info.vid == m.vid and info.pid == m.pid then
      return true
    end
  end
  return false
end

local function wheel_frame(wheel, hires)
  local f = {}
  if hires ~= 0 then f[#f + 1] = { usage = evdev.REL_WHEEL_HI_RES, value = hires } end
  if wheel ~= 0 then f[#f + 1] = { usage = evdev.REL_WHEEL, value = wheel } end
  return f
end

-- Several held ticks are re-injected as one frame with summed values.
local function merged(ticks)
  local w, h = 0, 0
  for _, t in ipairs(ticks) do
    w = w + t.wheel
    h = h + t.hires
  end
  return wheel_frame(w, h)
end

local function without_vertical_wheel(frame)
  local out = {}
  for _, ev in ipairs(frame) do
    if ev.usage ~= evdev.REL_WHEEL and ev.usage ~= evdev.REL_WHEEL_HI_RES then
      out[#out + 1] = ev
    end
  end
  return out
end

local function attach(device)
  local accepted_dir = 0    -- direction of the last forwarded tick (0 = none yet)
  local last_time    = 0    -- timestamp (us) of the previous wheel tick, any direction
  local held         = {}   -- withheld opposite ticks, oldest first: { wheel, hires }

  device:connect("evdev-frame", function(dev, frame, timestamp)
    local wheel, hires = 0, 0
    for _, ev in ipairs(frame) do
      if ev.usage == evdev.REL_WHEEL then
        wheel = wheel + ev.value
      elseif ev.usage == evdev.REL_WHEEL_HI_RES then
        hires = hires + ev.value
      end
    end

    local dir = sign(hires ~= 0 and hires or wheel)
    if dir == 0 then
      return nil -- no vertical wheel movement in this frame
    end

    local prev_time = last_time
    last_time = timestamp

    trace(string.format("dir=%+d wheel=%d hires=%d dt=%.1fms accepted_dir=%+d held=%d",
      dir, wheel, hires, (timestamp - prev_time) / 1000, accepted_dir, #held))

    -- First tick ever, or same direction as before: forward.
    if accepted_dir == 0 or dir == accepted_dir then
      if #held > 0 then
        log("dropped " .. #held .. " reverse tick(s)")
        held = {}
      end
      accepted_dir = dir
      return nil
    end

    -- Opposite direction, but long after the previous tick: genuine reversal.
    if timestamp - prev_time > CONFIG.window_us then
      if #held > 0 then
        dev:prepend_frame(merged(held))
        held = {}
      end
      accepted_dir = dir
      return nil
    end

    -- Opposite direction inside the window: hold it.
    held[#held + 1] = { wheel = wheel, hires = hires }

    if #held >= CONFIG.confirm_ticks then
      -- Genuine reversal. Release the older held ticks ahead of this one so
      -- nothing is lost; the current tick passes through unmodified.
      local older = {}
      for i = 1, #held - 1 do older[i] = held[i] end
      log("confirmed reversal after " .. #held .. " ticks")
      dev:prepend_frame(merged(older))
      held = {}
      accepted_dir = dir
      return nil
    end

    -- Still undecided: withhold the wheel movement (keep any non-wheel events).
    return without_vertical_wheel(frame)
  end)

  device:connect("device-removed", function()
    held = {}
  end)
end

libinput:connect("new-evdev-device", function(device)
  if wants(device) then
    log("active on " .. device:name())
    attach(device)
  end
end)
